//all players list
GET http://localhost:3000/players/

//specific player
###
GET http://localhost:3000/players/2/

//update specific player
###
PUT http://localhost:3000/players/2/
Content-Type:application/json

{
  "playerName": "Raju"
}

//get specific match details
###
GET http://localhost:3000/matches/2/

//specific player matches played
###
GET http://localhost:3000/players/2/matches/

//specific match players
###
GET http://localhost:3000/matches/1/players/

//specific player scores
###
GET http://localhost:3000/players/1/playerScores/